const palabras = [
  {
    referencia: "alba",
    signos: [
      [
        { nombre: "cabeza", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "tronco", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "brazoSuperiorDerecho",
          rotation: 3,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorDerecho",
          rotation: -34,
          rotateX: 153,
          rotateY: 180,
          zIndex: 11,
        },
        {
          nombre: "manoDerecha",
          rotation: 29,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho1",
          rotation: 0,
          rotateX: 67,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho2",
          rotation: 0,
          rotateX: 70,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho4",
          rotation: 0,
          rotateX: 74,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho",
          rotation: 16,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoSuperiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoIzquierda",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoDerecho",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        { nombre: "boca", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "nariz", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
      ],
    ],
  },

  {
    referencia: "cumpleaños",
    signos: [
      [
        { nombre: "cabeza", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "tronco", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "brazoSuperiorDerecho",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorDerecho",
          rotation: 169,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "manoDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 198,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 12,
        },
        {
          nombre: "dedoDerecho2",
          rotation: 0,
          rotateX: 39,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 12,
        },
        {
          nombre: "pulgarDerecho",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoSuperiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoIzquierda",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoDerecho",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        { nombre: "boca", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "nariz", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "pulgarDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho11",
          rotation: 185,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho22",
          rotation: 163,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho33",
          rotation: 0,
          rotateX: 160,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho44",
          rotation: 0,
          rotateX: 58,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho444",
          rotation: 0,
          rotateX: 45,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
      ],
    ],
  },
  {
    referencia: "hola",
    signos: [
      [
        { nombre: "cabeza", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "tronco", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "brazoSuperiorDerecho",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorDerecho",
          rotation: 102,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "manoDerecha",
          rotation: 80,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho",
          rotation: 339,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoSuperiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoIzquierda",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo",
          rotation: 34,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoDerecho",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        { nombre: "boca", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "nariz", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
      ],
    ],
  },
  {
    referencia: "adios",
    signos: [
      [
        { nombre: "cabeza", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "tronco", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "brazoSuperiorDerecho",
          rotation: 18,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorDerecho",
          rotation: 116,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoDerecha",
          rotation: 40,
          rotateX: 0,
          rotateY: 167,
          zIndex: null,
        },
        {
          nombre: "dedoDerecho1",
          rotation: 177,
          rotateX: 0,
          rotateY: 167,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho2",
          rotation: 177,
          rotateX: 0,
          rotateY: 167,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho3",
          rotation: 174,
          rotateX: 0,
          rotateY: 167,
          zIndex: 11,
        },
        {
          nombre: "dedoDerecho4",
          rotation: 174,
          rotateX: 0,
          rotateY: 167,
          zIndex: 11,
        },
        {
          nombre: "pulgarDerecho",
          rotation: 339,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoSuperiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoIzquierda",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo",
          rotation: 34,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoDerecho",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        { nombre: "boca", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "nariz", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
      ],
    ],
  },
  {
    referencia: "gracias",
    signos: [
      [
        { nombre: "cabeza", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "tronco", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "brazoSuperiorDerecho",
          rotation: 18,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorDerecho",
          rotation: 199,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "manoDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho",
          rotation: 339,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoSuperiorIzquierdo",
          rotation: 18,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorIzquierdo",
          rotation: 139,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoIzquierda",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo",
          rotation: 34,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoDerecho",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        { nombre: "boca", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "nariz", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
      ],
      [
        { nombre: "cabeza", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "tronco", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "brazoSuperiorDerecho",
          rotation: 18,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorDerecho",
          rotation: 104,
          rotateX: 0,
          rotateY: 0,
          zIndex: 11,
        },
        {
          nombre: "manoDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho",
          rotation: 339,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoSuperiorIzquierdo",
          rotation: 34,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "brazoInferiorIzquierdo",
          rotation: 110,
          rotateX: 132,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "manoIzquierda",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo2",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo3",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo4",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo",
          rotation: 34,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoIzquierdo",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "ojoDerecho",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pupilaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaDerecha",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "orejaIzquierda",
          rotation: 0,
          rotateX: "center center",
          rotateY: 0,
          zIndex: 10,
        },
        { nombre: "boca", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        { nombre: "nariz", rotation: 0, rotateX: 0, rotateY: 0, zIndex: 10 },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "sin_nombre",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarDerecho1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "pulgarIzquierdo1",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoDerecho444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo44",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo444",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo33",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo333",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo22",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo222",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo11",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
        {
          nombre: "dedoIzquierdo111",
          rotation: 0,
          rotateX: 0,
          rotateY: 0,
          zIndex: 10,
        },
      ],
    ],
  },
];
